--YA ESTAN CREADAS TODAS LAS TABLAS EN LA BASE DE DATOS
--YA ESTAN CREADOS EL ROL Y USUARIO DE ACCESO EN LA BASE DE DATOS DE MYSQL

---- Rol ADMIN
--INSERT INTO roles (nombre_rol, descripcion)
--VALUES ('Admin', 'Administrador del sistema');

-- Usuario de acceso
--INSERT INTO usuarios (
--    nombre_completo,
--    username,
--    password,
--    telefono,
--    direccion,
--    correo_electronico,
--    id_rol
--) VALUES (
--    'Daniel Lopez',
--    'sysadmin',
--    '827ccb0eea8a706c4c34a16891f84e7b',
--    '7554-3463',
--    'San Salvador',
--    'daniel@gmail.com',
--    1
--);
